### ISSUE TITLE
Failed to activate the atom-csscomb package

### ISSUE THREAD

**Issue by jruivo** [1000ch/atom-csscomb#13]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.13
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-csscomb](https://github.com/1000ch/atom-csscomb) package, v1.8.4
### Stack Trace

Failed to activate the atom-csscomb package

```
At Cannot find module 'csscomb'

Error: Cannot find module 'csscomb'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\José\.atom\packages\atom-csscomb\index.js:15:16)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\package.js:761:34)
  at Package.module.exports.Package.activateConfig (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\package.js:263:14)
  at Package.module.exports.Package.activateNow (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\package.js:241:14)
  at C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\package.js:838:25
  at Emitter.module.exports.Emitter.emit (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\command-registry.js:221:20)
  at CommandRegistry.handleCommandEvent (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\atom.asar\renderer\api\lib\remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\window-event-handler.js:157:33)
  at HTMLDocument.handler (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\José\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```
### Commands

```
     -0:32.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:32 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:31.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:30.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:29.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:29.7.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:28.7.0 core:undo (atom-text-editor.editor.is-focused)
  2x -0:27.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:27.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:27.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:27.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:26.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:26.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  5x -0:25.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:23.5.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:10.7.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "emmet"
    ]
  },
  "atom-csscomb": {
    "configureWithJSON": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.12
atom-csscomb, v1.8.4
auto-indent, v0.5.0
color-picker, v2.0.11
highlight-line, v0.11.0
linter, v1.5.2
minimap, v4.13.3
project-manager, v2.5.1

# Dev
No dev packages
```

**Comment by 1000ch** [comment]
I guess Atom failed to install `csscomb` on installing `atom-csscomb`.
Would you install `atom-csscomb` again?
