### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by Epyon616** [1000ch/atom-csscomb#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-csscomb](https://github.com/1000ch/atom-csscomb) package, v0.7.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /Users/lee/.atom/packages/atom-csscomb/lib/csscomb.coffee:34

TypeError: Cannot read property 'getGrammar' of undefined
  at Object.module.exports.execute (/Users/lee/.atom/packages/atom-csscomb/lib/csscomb.coffee:34:25)
  at atom-workspace.<anonymous> (/Users/lee/.atom/packages/atom-csscomb/lib/csscomb.coffee:21:64)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at EventEmitter.emit (events.js:116:17)

```
### Commands

```
     -0:16.4 tree-view:copy (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:03.3 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-railscasts.theme-atom-dark-ui)
     -0:00.6 csscomb:execute (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "railscasts"
    ],
    "projectHome": "/Users/lee/code",
    "destroyEmptyPanes": false
  }
}
```
### Installed Packages

``` coffee
# User
ScssBundle, v0.4.0
atom-backbone, v0.6.0
atom-csscomb, v0.7.0
coffee-lint, v0.7.3
coffee-refactor, v0.6.2
compass, v0.7.5
cucumber, v0.4.0
emacs-mode, v0.0.29
html2haml, v0.3.0
javascript-snippets, v1.0.0
js-refactor, v0.3.0
language-haml, v0.14.0
language-liquid, v0.2.0
language-yaml, v0.21.0
linter-scss-lint, v0.0.11
railscasts, v0.2.2
refactor, v0.4.1
rspec-snippets, v0.4.0

# Dev
No dev packages
```

**Comment by 1000ch** [comment]
@StealthyGecko `atom.workspace.getActiveTextEditor()` is newer API to get current editor view.
So please update your Atom to newest (`0.192`).

**Comment by Epyon616** [comment]
@1000ch thanks, I realise this was the case shortly after submitting this bug :)
