### ISSUE TITLE
Failed to load the atom-csscomb package

### ISSUE THREAD

**Issue by dfernandez79** [1000ch/atom-csscomb#6]
This happens with the new versions of Atom:

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-csscomb](https://github.com/1000ch/atom-csscomb) package, v0.7.0
### Stack Trace

Failed to load the atom-csscomb package

```
At Cannot read property 'getDirectories' of null

TypeError: Cannot read property 'getDirectories' of null
    at Object.<anonymous> (/Users/diegof/.atom/packages/atom-csscomb/lib/csscomb.coffee:13:40)
    at Object.<anonymous> (/Users/diegof/.atom/packages/atom-csscomb/lib/csscomb.coffee:85:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Users/diegof/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (/Users/diegof/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:677:34)
    at /Users/diegof/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:28
```
### Installed Packages

``` coffee
# User
atom-csscomb, v0.7.0
coffee-compile, v0.13.0
emmet, v2.3.8
file-icons, v1.5.4
html2jade, v0.7.0
jsonpp, v0.0.6
language-jade, v0.4.0
linter, v0.12.1
linter-coffeelint, v0.2.1
linter-jshint, v0.1.2
react, v0.11.6

# Dev
No dev packages
```

**Comment by 1000ch** [comment]
@dfernandez79 Sorry for delay.
Still getting error with Atom 0.196.0 + atom-csscomb 0.7.1?
I have tried (`atom --one`) but may got no errors.
